### ISSUE TITLE
how long will full implementation be available

### ISSUE THREAD

**Issue by XA23i** [kriskrisliu/NoisyQuant#2]
Hi, there is a huge gap between 81.90(reported in your paper) and  72.45(simple implementation).

**Comment by kriskrisliu** [comment]
Thank you for your interest in our work!
The code we currently provide is a simple implementation, primarily to demonstrate the core technology of NoisyQuant. We have not incorporated any additional tricks, such as weight/activation clipping. You can use NoisyQuant in conjunction with some existing quantization schemes. For example, in our paper, we integrated NoisyQuant with EasyQuant. The accuracy of 81.90% mentioned in our paper is an improvement from EasyQuant's baseline of 81.42%.

**Comment by XA23i** [comment]
Thank you for your quick response, I'll try it.
